/* Generated by OCHGen */

#import <Foundation/Foundation.h>

@interface NSObject (PEDynamicDelegation)

+(void)setDynamicDelegateClassName:(NSString*)dynamicDelegateClassName;
-(void)setDynamicDelegate:(id)dynamicDelegate;
+(void) swizzleMethods;
-(id) replacement_init;
-(id)replacement_forwardingTargetForSelector:(SEL)selector;
-(BOOL) replacement_respondsToSelector:(SEL)selector;


@end
